### ISSUE TITLE
mimik OBS4MIP or add other products

### ISSUE THREAD

**Issue by aaronspring** [luke-gregor/dataBrewery#1]
There is this OBS4MIP, which sounds nice, but I dont know any research center that downloads these obs, some licencing problems apparently. https://esgf-node.llnl.gov/search/obs4mips/

Maybe this is out of scope for dataBrewery, but adding a few of these datasets like HadCrut or HadISST would be nice.

I discussed the obs4mip in combination with intake with @andersy005 two weeks ago.

**Comment by lukegre** [comment]
If it has a URL and there's an auth package in Python, then we can add this. 
@aaronspring check out the `config_template.yml` file in the `dev` branch. IT should give you a better idea of what dataBrewery does. The yaml file is validated by catalog.schema

**Comment by aaronspring** [comment]
checked this out. looks quite nice. and similar to `intake-xarray` although I see you have some formalized postprocessing and some kind of caching/downloading.

**Comment by lukegre** [comment]
Yep, the whole idea is to download data that sits on authorised FTP and HTTPS servers and store it locally (on a local data server or something like that). The post processing is still in the pipeline, but the idea would be that a user stores post processed data on their local repo. Might actually be a use case for `intake-xarray`?

Re OBS4MIP: I've done a little bit of digging around and I think this will be possible through the python client. Will require the user to set up the ESGF client first though. Then one can then make a download protocol for ESGF data (databrewery/download.py). https://esgf-pyclient.readthedocs.io/en/latest/notebooks/examples/download.html

**Comment by aaronspring** [comment]
Yes. Intake xarray could nicely use local data. I think it even allows some remote data and caching even.

**Comment by lukegre** [comment]
Hmm, I did look for that. Have you used it in that way at all?

**Comment by aaronspring** [comment]
I used intake-xarray: https://gitlab.dkrz.de/m300524/pymistral/-/blob/master/intake/obs.yml

**Comment by lukegre** [comment]
We should totally just make this an extension for intake. Add a few args in intake that specify the login details. Most of the work has been to download... though, might be a bit buggy.
